font:
  normal:
    family: monospace
    style: Regular

  bold:
    family: monospace
    style: Bold

  italic:
    family: monospace
    style: Italic

  bold_italic:
    family: monospace
    style: Bold Italic

  size: 7.5
window:
  opacity: 0.72


colors:
  primary:
    background: '#000000'
    foreground: '#dcdccc'

    # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '#000000'
    cursor: '#dcdccc'

  # Normal colors
  normal:
    black:   '#3f3f3f'
    red:     '#705050'
    green:   '#60b48a'
    yellow:  '#dfaf8f'
    blue:    '#506070'
    magenta: '#dc8cc3'
    cyan:    '#8cd0d3'
    white:   '#dcdccc'

    # Bright colors
  bright:
    black:   '#666666'
    red:     '#ff3334'
    green:   '#9ec400'
    yellow:  '#f0c674'
    blue:    '#81a2be'
    magenta: '#b77ee0'
    cyan:    '#54ced6'
    white:   '#eeeeee'

shell:
  program: /bin/zsh
