general.import=["~/.cache/wal/colors-alacritty.toml"]

[font]
size = 7.5

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"

[window]
opacity = 0.72

[terminal]
