# autogenerated by txs
#include:ifluatex
#include:ifxetex
#include:inputenc
#include:luatexbase
#include:xetex-inputenc
\DeclareInputMath{arg1}#S
\DeclareInputText{arg1}{arg2}#S
\IeC#S
\InputNonUtfFile{arg1}#S
\InputUtfFile{arg1}#S
\inputencoding{arg1}#S
\lIE#S
ifxetex.sty#S
inputenc.sty#S
