# autogenerated by txs
#include:GemeinsameDaten
#include:bookmark
#include:calc
#include:lastpage
#include:layout
#include:lipsum
#include:pdfpages
\anhang#S
\anhangB#S
\begin{bildSeiteB}#S
\begin{bildSeite}#S
\bildZentriert{arg1}{arg2}#S
\end{bildSeiteB}#S
\end{bildSeite}#S
