# autogenerated by txs
#include:auxhook
#include:etexcmds
#include:infwarerr
#include:kvdefinekeys
#include:kvsetkeys
#include:ltxcmds
#include:makerobust
#include:pdftexcmds
\csname#S
\noexpand#S
\string#S
\thepage#S
\write#S
\default#S
\page#S
\zifrefundefined#S
