#! /bin/sh

setxkbmap -option grp:alt_shift_toggle -layout de -variant ,phonetic &		
xsetroot -cursor_name left_ptr							#Mouse

####### KEYRING
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

###### AUTOSTART
nm-applet &
sxhkd &
dropbox &
kdeconnect-indicator &
##################

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/bspwm/panel/lemonbar.sh &
feh --bg-fill /data/Bilder/Wallpaper/Fractal/synergy_by_zy0rg-d2ypdzp.png &

sleep 1
stalonetray -i 16 --max-geometry 4x1 --scrollbars horizontal  -d "all" -t "true"  --scrollbars-step "16" &



telegram-desktop &





compton 




############ Garbage Collector

killall telegram-desktop
killall dropbox
killall lemonbar.sh
killall nm-applet
killall stalonetray

