#! /bin/sh

setxkbmap -option grp:alt_shift_toggle -layout de -variant ,phonetic &		#Keyboard to DE
xsetroot -cursor_name left_ptr							#Mouse

####### KEYRING
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)	#Keyring itself
export SSH_AUTH_SOCK	
							#Can't remember is important, has to do with the Keyring
####### Autostart PRE
# Stuff that can't be loaded late out of whatever reason DO NOT LIKE
nm-applet &		# Applet's broken as fuck anyway. fix it FFS
#######

####### BSPCWM implementation
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


##### System Stuff
bash ~/.config/bspwm/panel/lemonbar.sh &
feh --bg-fill /data/Bilder/Wallpaper/Fractal/synergy_by_zy0rg-d2ypdzp.png &



sleep 1				#in Case of Programs not loaded for satlonetray
###### AUTOSTART
sxhkd &
dropbox &
kdeconnect-indicator &
telegram-desktop &		# this on especially
##################



compton 




############ Garbage Collector

killall telegram-desktop
killall dropbox
killall lemonbar
killall bash
killall lemonbar.sh
killall nm-applet
killall stalonetray

